localStorage.setItem('key','value')
localStorage.getItem('key')
localStorage.remove('key')
localStorage.clear()
localStorage.setItem('username','pawn')
localStorage.getItem('username'
                    )
localStorage.getItem('username')
localStorage.clear()
